import { StyleSheet } from "react-native";

export const colors = {
  bg: "#F6FAF8", primary: "#0F6E56", primaryLight: "#E1F5EE", mid: "#1D9E75",
  text: "#0B2E26", muted: "#5F6B68", border: "#D6E4DE", white: "#FFFFFF",
  amber: "#EF9F27", amberBg: "#FAEEDA", amberText: "#633806",
  red: "#A32D2D", redBg: "#FCEBEB", redBorder: "#F09595", redBar: "#E24B4A",
};

// EXTERNAL STYLING
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg, alignItems: "center" },
  content: { flex: 1, width: "100%", maxWidth: 560 },
  scroll: { paddingHorizontal: 18, paddingBottom: 24 },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  rowCenter: { flexDirection: "row", alignItems: "center" },
  muted: { color: colors.muted, fontSize: 13, fontWeight: "600" },
  greeting: { color: colors.muted, fontSize: 14, fontWeight: "600" },
  userName: { color: colors.text, fontSize: 22, fontWeight: "800" },
  iconBtn: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" },
  hero: { backgroundColor: colors.primary, borderRadius: 24, padding: 20, marginTop: 18, overflow: "hidden", minHeight: 130, justifyContent: "center" },
  heroLabel: { color: colors.primaryLight, fontSize: 13, fontWeight: "700" },
  heroTitle: { color: colors.white, fontSize: 26, fontWeight: "800", marginTop: 2 },
  heroInfo: { color: colors.primaryLight, fontSize: 14, fontWeight: "600", marginTop: 4 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: "800" },
  barTrack: { height: 10, borderRadius: 5, backgroundColor: colors.border, marginTop: 8 },
  barFill: { height: 10, borderRadius: 5, backgroundColor: colors.mid },
  card: { flexDirection: "row", alignItems: "center", backgroundColor: colors.white, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 14, marginTop: 10 },
  cardIcon: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center", marginRight: 12 },
  medName: { color: colors.text, fontSize: 17, fontWeight: "800" },
  medInfo: { color: colors.muted, fontSize: 13, fontWeight: "600", marginTop: 2 },
  chip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 10 },
  chipText: { fontSize: 12, fontWeight: "800" },
  formBox: { backgroundColor: colors.white, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 16, marginTop: 20 },
  input: { borderWidth: 1.5, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, marginTop: 10, fontSize: 15, fontWeight: "600", color: colors.text, backgroundColor: colors.bg },
  inputRow: { flexDirection: "row", gap: 10 },
  primaryBtn: { backgroundColor: colors.primary, borderRadius: 16, paddingVertical: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", marginTop: 14 },
  primaryBtnText: { color: colors.white, fontSize: 17, fontWeight: "800", marginLeft: 8 },
  nav: { flexDirection: "row", justifyContent: "space-around", backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10, width: "100%" },
  navItem: { alignItems: "center", paddingHorizontal: 16 },
  navLabel: { fontSize: 12, fontWeight: "700", marginTop: 2 },
  alertCard: { backgroundColor: colors.redBg, borderWidth: 1, borderColor: colors.redBorder, borderRadius: 20, padding: 16, marginTop: 16 },
  alertTitle: { color: "#791F1F", fontSize: 17, fontWeight: "800", marginLeft: 8 },
  alertText: { color: "#791F1F", fontSize: 14, fontWeight: "600", marginTop: 6 },
  alertBtn: { backgroundColor: colors.red, borderRadius: 14, paddingVertical: 13, alignItems: "center", marginTop: 12 },
  chartBox: { backgroundColor: colors.white, borderRadius: 20, borderWidth: 1, borderColor: colors.border, padding: 16, marginTop: 16 },
  chartRow: { flexDirection: "row", alignItems: "flex-end", height: 110, marginTop: 14, gap: 8 },
  chartCol: { flex: 1, height: "100%", justifyContent: "flex-end" },
  chartDay: { flex: 1, textAlign: "center", color: colors.muted, fontSize: 12, fontWeight: "700" },
  remindBg: { flex: 1, backgroundColor: colors.primaryLight, alignItems: "center" },
  remindTitle: { color: colors.text, fontSize: 26, fontWeight: "800", textAlign: "center", marginTop: 20 },
  remindName: { color: colors.primary, fontSize: 22, fontWeight: "800", marginTop: 8 },
  remindInfo: { color: "#085041", fontSize: 15, fontWeight: "600", marginTop: 4 },
  bigBtn: { backgroundColor: colors.primary, borderRadius: 22, paddingVertical: 22, flexDirection: "row", alignItems: "center", justifyContent: "center", width: "100%" },
  bigBtnText: { color: colors.white, fontSize: 21, fontWeight: "800", marginLeft: 10 },
  snooze: { color: "#085041", fontSize: 16, fontWeight: "700", textAlign: "center", padding: 16 },
});